/**
 * Draws `public/og-cover.png`, the 1200x630 card Messages, Slack and a forum
 * post render in place of the link, and `public/apple-touch-icon.png`.
 *
 * These are the two assets in the repo that are generated rather than
 * written, and the two that cannot be generated by either deploy workflow:
 * rasterising needs a browser, and neither workflow installs one. So the PNGs
 * are committed, and this script is how they are re-made when the page they
 * stand for changes. Run it by hand:
 *
 *     node scripts/og-cover.mjs
 *
 * Two things it leans on are outside `package.json`. `rolldown`, which vite
 * brings, bundles `src/lib` so a plain node script can import it. The browser
 * is whatever the last `npx playwright install chromium` left in the
 * Playwright cache — the headless shell is driven directly, by its own
 * command line, so nothing has to be installed to talk to it; `CHROME_PATH`
 * points at any other Chromium build instead.
 *
 * The curve on the card is the real one. `marginalRateCurve` is bundled out
 * of `src/lib` and sampled for the scenario the page opens on, so the shape
 * a reader sees in the preview is the shape they land on — and if the
 * arithmetic under it ever moves, re-running this moves the picture with it.
 * A drawn-by-hand hump would go on claiming 22.2% long after the statute
 * stopped saying so.
 *
 * The faces are the page's own, fetched from Google Fonts while the card is
 * drawn, which is why this needs a network as well as a browser: a card set
 * in Georgia would be a different page's card.
 */
import { build } from 'rolldown';
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { tmpdir, homedir } from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC = join(ROOT, 'public');

/* ── The arithmetic ──────────────────────────────────────────────────────── */

/**
 * `src/lib` is TypeScript and this is a plain node script, so the module has
 * to be bundled before it can be imported. Everything the card needs comes
 * from the two files the page itself reads its opening state out of.
 */
async function loadTaxModule() {
  const dir = mkdtempSync(join(tmpdir(), 'og-cover-'));
  const entry = join(dir, 'entry.ts');
  const out = join(dir, 'bundle.mjs');
  writeFileSync(
    entry,
    `export * from ${JSON.stringify(join(ROOT, 'src/torpedo/lib/tax/index'))};\n` +
      `export * from ${JSON.stringify(join(ROOT, 'src/torpedo/lib/scenarioUrl'))};\n`,
  );
  await build({ input: entry, output: { file: out, format: 'esm' }, platform: 'node', logLevel: 'silent' });
  const mod = await import(pathToFileURL(out).href);
  rmSync(dir, { recursive: true, force: true });
  return mod;
}

/* ── The browser ─────────────────────────────────────────────────────────── */

/**
 * The newest Chromium build in the Playwright cache, headless shell first,
 * and `CHROME_PATH` ahead of all of it.
 */
function chromiumPath() {
  if (process.env.CHROME_PATH) return process.env.CHROME_PATH;
  const cache =
    process.platform === 'darwin'
      ? join(homedir(), 'Library/Caches/ms-playwright')
      : join(homedir(), '.cache/ms-playwright');
  if (!existsSync(cache)) return null;
  const leaves = [
    'chrome-headless-shell-mac-arm64/chrome-headless-shell',
    'chrome-headless-shell-linux64/chrome-headless-shell',
    'chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',
    'chrome-linux/chrome',
  ];
  const builds = readdirSync(cache)
    .filter((name) => /^chromium(_headless_shell)?-\d+$/.test(name))
    .sort((a, b) => Number(b.split('-').pop()) - Number(a.split('-').pop()));
  for (const dir of builds) {
    for (const leaf of leaves) {
      const candidate = join(cache, dir, leaf);
      if (existsSync(candidate)) return candidate;
    }
  }
  return null;
}

/** The page's own faces, from the one host it loads them from. */
const FONTS =
  'https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400..700;1,6..72,400..700&family=IBM+Plex+Mono:wght@400;500&display=swap';

/**
 * Rasterise one SVG string at its own size.
 *
 * The SVG is wrapped in a page that links the fonts, and the browser is given
 * a virtual-time budget long enough for them to arrive before the screenshot
 * is taken — the same shell flag that lets a headless capture wait out a
 * network fetch without a driver.
 */
function rasterise(executablePath, svg, { width, height, path }) {
  const dir = mkdtempSync(join(tmpdir(), 'og-cover-page-'));
  const page = join(dir, 'page.html');
  writeFileSync(
    page,
    `<!doctype html><html><head><meta charset="utf-8">` +
      `<link rel="stylesheet" href="${FONTS}"></head>` +
      `<body style="margin:0;background:transparent">${svg}</body></html>`,
  );
  execFileSync(
    executablePath,
    [
      '--headless',
      '--disable-gpu',
      '--hide-scrollbars',
      `--window-size=${width},${height}`,
      '--virtual-time-budget=15000',
      `--screenshot=${path}`,
      pathToFileURL(page).href,
    ],
    { stdio: 'ignore' },
  );
  rmSync(dir, { recursive: true, force: true });
  console.log(`wrote ${path.replace(`${ROOT}/`, '')}  ${width}x${height}`);
}

/* ── The card ────────────────────────────────────────────────────────────── */

/** The page's own tokens. Kept in step by `the cover` in src/guards/meta.test.ts. */
const SURFACE = '#f7f3eb';
const INK = '#261d16';
const INK_BRIGHT = '#160d07';
const INK_SOFT = '#50453d';
const INK_MUTED = '#6c6158';
const EDGE = '#c9c3ba';
const ACCENT = '#2769b7';
const AMBER = '#b76100';
const ROSE = '#c03a51';

const SERIF = "'Newsreader', Georgia, 'Times New Roman', serif";
const MONO = "'IBM Plex Mono', Menlo, Consolas, monospace";

const WIDTH = 1200;
const HEIGHT = 630;

/** The plot, in card coordinates. */
const PLOT = { left: 72, right: 1128, top: 300, bottom: 540 };

const money = (n) => `$${Math.round(n / 1000)}K`;

function cover(curve, hook) {
  const xs = curve.map((p) => p.totalIncome);
  const minX = Math.min(...xs);
  const maxX = Math.max(...xs);
  // A fixed ceiling rather than the curve's own peak: the card is one picture
  // of one scenario, and a y-axis that rescales itself would redraw the same
  // 22.2% hump at a different height every time the default moved.
  const maxY = 30;

  const x = (income) => PLOT.left + ((income - minX) / (maxX - minX)) * (PLOT.right - PLOT.left);
  const y = (rate) => PLOT.bottom - (rate / maxY) * (PLOT.bottom - PLOT.top);

  const line = curve.map((p) => `${x(p.totalIncome).toFixed(1)},${y(p.marginalRate).toFixed(1)}`);
  const path = `M${line.join('L')}`;
  const area = `${path}L${x(maxX).toFixed(1)},${PLOT.bottom}L${x(minX).toFixed(1)},${PLOT.bottom}Z`;

  // The hump, not the high ground: the point worth labelling is the local
  // maximum the benefit's inclusion makes — the highest rate reached *before*
  // the curve falls back — and the valley is where it falls back to. Both
  // are plateaux, so each label is pinned to the middle of its own run.
  const fallBack = curve.findIndex((p, i) => i > 0 && p.marginalRate < curve[i - 1].marginalRate);
  const humpIndex =
    fallBack > 0
      ? fallBack - 1
      : curve.indexOf(curve.reduce((a, b) => (b.marginalRate > a.marginalRate ? b : a)));
  const valleyIndex =
    fallBack > 0
      ? curve.reduce((best, p, i) => (i > humpIndex && p.marginalRate < curve[best].marginalRate ? i : best), humpIndex + 1)
      : humpIndex;

  const middleOfRun = (index) => {
    const rate = curve[index].marginalRate;
    let first = index;
    let last = index;
    while (first > 0 && curve[first - 1].marginalRate === rate) first -= 1;
    while (last < curve.length - 1 && curve[last + 1].marginalRate === rate) last += 1;
    return curve[Math.round((first + last) / 2)];
  };

  const hump = middleOfRun(humpIndex);
  const valley = middleOfRun(valleyIndex);

  const gridRates = [0, 10, 20, 30];
  const ticks = [50_000, 100_000, 150_000].filter((v) => v > minX && v < maxX);

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${WIDTH}" height="${HEIGHT}" viewBox="0 0 ${WIDTH} ${HEIGHT}" font-family="${SERIF}">
  <defs>
    <pattern id="hatch" width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
      <line x1="0" y1="0" x2="0" y2="7" stroke="${ACCENT}" stroke-width="1.2" stroke-opacity="0.32"/>
    </pattern>
  </defs>

  <rect width="${WIDTH}" height="${HEIGHT}" fill="${SURFACE}"/>
  <rect width="${WIDTH}" height="8" fill="${INK}"/>

  <text x="72" y="52" fill="${INK}" font-family="${MONO}" font-size="15" letter-spacing="3">TAX TORPEDO</text>
  <text x="1128" y="52" fill="${INK_MUTED}" font-family="${MONO}" font-size="15" letter-spacing="3" text-anchor="end">TAX YEAR ${hook.year} · FEDERAL ONLY</text>
  <line x1="72" y1="64" x2="1128" y2="64" stroke="${INK}" stroke-width="1"/>

  <text x="72" y="140" fill="${INK_BRIGHT}" font-size="66" font-weight="500" letter-spacing="-1.4" style="font-variation-settings: 'opsz' 72">How much can you</text>
  <text x="72" y="204" fill="${INK_BRIGHT}" font-size="66" font-weight="500" letter-spacing="-1.4" style="font-variation-settings: 'opsz' 72">take out this year?</text>
  <text x="72" y="250" fill="${INK_SOFT}" font-size="21">What the next dollar out of an IRA actually costs, drawn across every</text>
  <text x="72" y="279" fill="${INK_SOFT}" font-size="21">income level — with Social Security dragged into the tax base behind it.</text>

  <text x="1128" y="112" fill="${INK_MUTED}" font-family="${MONO}" font-size="13" letter-spacing="2.6" text-anchor="end">YOUR BRACKET SAYS</text>
  <text x="1128" y="172" fill="${INK_MUTED}" font-size="62" text-anchor="end" style="font-variation-settings: 'opsz' 72; text-decoration: line-through; text-decoration-color: ${ROSE}; text-decoration-thickness: 2.5px">${hook.valley}%</text>
  <text x="1128" y="204" fill="${INK_MUTED}" font-family="${MONO}" font-size="13" letter-spacing="2.6" text-anchor="end">THE NEXT DOLLAR COSTS</text>
  <text x="1128" y="284" fill="${AMBER}" font-size="88" font-weight="500" letter-spacing="-2.6" text-anchor="end" style="font-variation-settings: 'opsz' 72">${hook.hump}%</text>

  ${gridRates
    .map(
      (rate) =>
        `<line x1="${PLOT.left}" y1="${y(rate).toFixed(1)}" x2="${PLOT.right}" y2="${y(rate).toFixed(1)}" stroke="${rate === 0 ? INK : EDGE}" stroke-width="1"/>` +
        `<text x="${PLOT.left - 12}" y="${(y(rate) + 5).toFixed(1)}" fill="${INK_MUTED}" font-family="${MONO}" font-size="15" text-anchor="end">${rate}%</text>`,
    )
    .join('\n  ')}

  <path d="${area}" fill="url(#hatch)"/>
  <path d="${path}" fill="none" stroke="${ACCENT}" stroke-width="4" stroke-linejoin="round" stroke-linecap="round"/>

  ${ticks
    .map(
      (income) =>
        `<line x1="${x(income).toFixed(1)}" y1="${PLOT.bottom}" x2="${x(income).toFixed(1)}" y2="${PLOT.bottom + 8}" stroke="${INK}" stroke-width="1"/>` +
        `<text x="${x(income).toFixed(1)}" y="${PLOT.bottom + 30}" fill="${INK_MUTED}" font-family="${MONO}" font-size="15" text-anchor="middle">${money(income)}</text>`,
    )
    .join('\n  ')}

  <circle cx="${x(hump.totalIncome).toFixed(1)}" cy="${y(hump.marginalRate).toFixed(1)}" r="8" fill="${AMBER}" stroke="${SURFACE}" stroke-width="2.5"/>
  <text x="${x(hump.totalIncome).toFixed(1)}" y="${(y(hump.marginalRate) - 24).toFixed(1)}" fill="${AMBER}" font-size="34" font-weight="500" text-anchor="middle" style="font-variation-settings: 'opsz' 72">${hump.marginalRate}%</text>
  <circle cx="${x(valley.totalIncome).toFixed(1)}" cy="${y(valley.marginalRate).toFixed(1)}" r="6.5" fill="${INK_MUTED}" stroke="${SURFACE}" stroke-width="2"/>
  <text x="${(x(valley.totalIncome) + 20).toFixed(1)}" y="${(y(valley.marginalRate) + 32).toFixed(1)}" fill="${INK_SOFT}" font-size="24" font-style="italic">back to ${valley.marginalRate}%</text>

  <text x="72" y="608" fill="${INK_MUTED}" font-family="${MONO}" font-size="15">ecao310.github.io/magnificent</text>
  <text x="1128" y="608" fill="${INK_MUTED}" font-size="17" font-style="italic" text-anchor="end">Total income →</text>
</svg>`;
}

/** The favicon, at the one size iOS asks for as a PNG. Paper with an ink edge. */
function touchIcon() {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180" viewBox="0 0 32 32">
  <rect width="32" height="32" fill="${SURFACE}"/>
  <rect x="0.5" y="0.5" width="31" height="31" fill="none" stroke="${INK}" stroke-width="1"/>
  <path d="M4 25H9L12 10H16L19 18H23L27 7" fill="none" stroke="${ACCENT}" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>
</svg>`;
}

/* ── The run ─────────────────────────────────────────────────────────────── */

const { marginalRateCurve, incomeAxisMax, torpedoPeak, defaultScenario, PAGE_TAX_YEAR } =
  await loadTaxModule();

const opening = defaultScenario();
const scenario = {
  filingStatus: opening.filingStatus,
  ssBenefit: opening.ssBenefit,
  // What the engine reads is a count, not the two boxes.
  seniors: opening.isSenior ? (opening.spouseIsSenior ? 2 : 1) : 0,
  muniInterest: opening.muniInterest,
};
const curve = marginalRateCurve(scenario, { maxIncome: incomeAxisMax(scenario), step: 250 });
const peak = torpedoPeak(curve);
if (!peak) {
  console.error('The opening scenario draws no torpedo, so there is nothing for the card to say.');
  process.exit(1);
}
const hook = { ...peak, year: PAGE_TAX_YEAR };
console.log(`curve: ${curve.length} points, ${money(curve[0].totalIncome)}–${money(curve.at(-1).totalIncome)} total income; ${hook.valley}% → ${hook.hump}%`);

const executablePath = chromiumPath();
if (!executablePath) {
  console.error('No chromium in the playwright cache. `npx playwright install chromium`, or set CHROME_PATH.');
  process.exit(1);
}

rasterise(executablePath, cover(curve, hook), { width: WIDTH, height: HEIGHT, path: join(PUBLIC, 'og-cover.png') });
rasterise(executablePath, touchIcon(), { width: 180, height: 180, path: join(PUBLIC, 'apple-touch-icon.png') });
